version: '1.0'
name: machine-code-native-master
displayName: Machine Code Native Master

triggers:
  push:
    branches:
      precise:
        - master
        - main

stages:
  - stage:
    name: check
    displayName: Check
    strategy: naturally
    trigger: auto

steps:
  - step: build@gcc
    name: rust_check_x64
    displayName: Rust Check x64
    gccVersion: 9.4
    commands:
      - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --profile minimal --default-toolchain 1.77.2
      - source "$HOME/.cargo/env"
      - rustup component add rustfmt
      - rustup target add x86_64-pc-windows-msvc
      - cargo fmt --check
      - cargo check --locked --target x86_64-pc-windows-msvc

  - step: build@gcc
    name: rust_check_x86
    displayName: Rust Check x86
    gccVersion: 9.4
    commands:
      - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --profile minimal --default-toolchain 1.77.2
      - source "$HOME/.cargo/env"
      - rustup target add i686-pc-windows-msvc
      - cargo check --locked --target i686-pc-windows-msvc
